Completed ticket 6
Storme419/stormes-fe-project pull request #2
Opened 2023-07-19 15:09 UTC by Storme419

2023-07-19 15:54 UTC, HeatherEver reviewed
Really nice work Storme - I would strongly consider moving all the comments logic into a separate component that ArticlePage so it is cleaner and more readable 
and this is just a suggestion but when an article has no comments it could be nice to display a message telling the user that :)

2023-07-20 09:46 UTC, Beth-McCormack requested changes
Nice work so far! 
Currently when there is an article with no comments (id 37) the comment section will continue to say 'loading comments'. Please add some feedback for the user for when theres no comments and resubmit when this is done

2023-07-20 10:45 UTC, mezzDavies approved these changes
This is approved but your implementation is actually a work-around because your API is not quite functioning as it should. See my other comment. All good just something you might need to fix.

2023-07-20 10:45 UTC, mezzDavies commented on src/Components/CommentSection.jsx
> +            setArticleComments([])
This setting the comments to an empty array shouldn't be necessary. Your API should return an empty array if there are no comments for a particular article. This is a work around. 😄  Don't worry about fixing this on your backend project right now though but just understand it is not quite right. 👍

2023-07-20 10:51 UTC, merged